### ISSUE TITLE
Terratest hangs when apply

### ISSUE THREAD

**Issue by r3kzi** [gruntwork-io/terratest#321]
My test hangs everytime at the same spot (creating configmap). After 10 minutes it gets killed.

```
TestTerraform 2019-06-14T08:45:33+02:00 command.go:96:   metadata.0.namespace:                "" => "ops"
TestTerraform 2019-06-14T08:45:33+02:00 command.go:96:   metadata.0.resource_version:         "" => "<computed>"
TestTerraform 2019-06-14T08:45:33+02:00 command.go:96:   metadata.0.self_link:                "" => "<computed>"
TestTerraform 2019-06-14T08:45:33+02:00 command.go:96:   metadata.0.uid:                      "" => "<computed>"
TestTerraform 2019-06-14T08:45:33+02:00 command.go:96: module.ops.module.prometheus_operator.kubernetes_config_map.istio_service_dashboard: Creating...
TestTerraform 2019-06-14T08:45:33+02:00 command.go:96:   data.%:                              "" => "1"
SIGQUIT: quit
PC=0x45b270 m=0 sigcode=0

goroutine 0 [idle]:
runtime.epollwait(0x7fff00000004, 0x7fffbf04ad80, 0xffffffff00000080, 0xc100000001, 0xffffffff0002b7a0, 0x1, 0x0, 0x1e922c9800000001, 0x7ff8, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:675 +0x20
runtime.netpoll(0xc000034501, 0x1)
	/usr/local/go/src/runtime/netpoll_epoll.go:71 +0x126
runtime.findrunnable(0xc000024000, 0x0)
	/usr/local/go/src/runtime/proc.go:2380 +0x51f
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2525 +0x21c
runtime.park_m(0xc000001080)
	/usr/local/go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000ac100, 0x54e1a6, 0xd, 0x555e70, 0x46e0d6)
	/usr/local/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc0000ac000)
	/usr/local/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc0000ac000, 0xc000055e30)
	/usr/local/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc00000c060, 0x649110, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc0000a8000, 0x0)
	/usr/local/go/src/testing/testing.go:1072 +0x162
main.main()
	_testmain.go:42 +0x13e

goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7ff81e922e38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000066678, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000066660, 0xc00017e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:263
os.(*File).Read(0xc00000e098, 0xc00017e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:108 +0x70
bufio.(*Scanner).Scan(0xc00007d8b8, 0x0)
	/usr/local/go/src/bufio/scan.go:213 +0xa4
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr(0xc0000ac100, 0x574720, 0xc00000e088, 0x574720, 0xc00000e098, 0x54e6f9, 0xf, 0x0, 0xc0000d0000)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:98 +0x314
github.com/gruntwork-io/terratest/modules/shell.RunCommandAndGetOutputE(0xc0000ac100, 0x54d6a0, 0x9, 0xc000022900, 0x4, 0x4, 0x54e6f9, 0xf, 0x0, 0xc00007db40, ...)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:74 +0x2df
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE.func1(0xc0000ac100, 0x2, 0x574060, 0xc00000e018)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/terraform/cmd.go:38 +0x10c
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE(0xc0000ac100, 0xc000017f80, 0x40, 0x0, 0x0, 0xc00007dd90, 0x40, 0x0, 0x0, 0x0)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/retry/retry.go:71 +0x300
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE(0xc0000ac100, 0xc00007df50, 0xc000022900, 0x4, 0x4, 0x0, 0x0, 0x0, 0xc00000c980)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/terraform/cmd.go:30 +0x1b5
github.com/gruntwork-io/terratest/modules/terraform.ApplyE(0xc0000ac100, 0xc00007df50, 0xc00000c980, 0x2, 0x2, 0xc0000a6400)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/terraform/apply.go:46 +0x1bf
github.com/gruntwork-io/terratest/modules/terraform.InitAndApplyE(0xc0000ac100, 0xc00007df50, 0x25, 0x539, 0xc000044710, 0x429dcf)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/terraform/apply.go:30 +0xec
github.com/gruntwork-io/terratest/modules/terraform.InitAndApply(0xc0000ac100, 0xc000044750, 0xc0000ac100, 0xc000044750)
	/home/chris/go/src/github.com/gruntwork-io/terratest/modules/terraform/apply.go:11 +0x39
_/home/chris/git-repos/kubernetes/bootstrap/test.TestTerraform(0xc0000ac100)
	/home/chris/git-repos/kubernetes/bootstrap/test/bootstrap_test.go:21 +0xc9
testing.tRunner(0xc0000ac100, 0x555e70)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x45b270
rdx    0x80
rdi    0x4
rsi    0x7fffbf04ad80
rbp    0x7fffbf04b380
rsp    0x7fffbf04ad40
r8     0x0
r9     0x0
r10    0xffffffff
r11    0x246
r12    0x0
r13    0x2
r14    0x2
r15    0x2
rip    0x45b270
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
```
My test.go file:

```
package main

import (
	"github.com/gruntwork-io/terratest/modules/terraform"
	"testing"
)

func TestTerraform(t *testing.T) {
	terraformOptions := &terraform.Options{
		// The path to where our Terraform code is located
		TerraformDir: "../../bootstrap",

		Upgrade: true,

	}

	// At the end of the test, run `terraform destroy` to clean up any resources that were created
	defer terraform.Destroy(t, terraformOptions)

	// This will run `terraform init` and `terraform apply` and fail the test if there are any errors
	terraform.InitAndApply(t, terraformOptions)
}
```

```
$ terraform version
Terraform v0.11.14
+ provider.aws v2.15.0
+ provider.helm v0.9.1
+ provider.kubernetes v1.7.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

```
$ go version
go version go1.12.6 linux/amd64
```

`terraform apply` and `terraform destroy` works like a charm!

no proxy.

**Comment by yorinasub17** [comment]
Since `terratest` just calls out to `terraform` using a subprocess, I think `terraform` is the one hanging. My best guess is that something about running in `terratest` is causing the api access to the kube cluster to fail that doesn't happen when manually using `terraform apply`. Hard to say without seeing the `terraform` module code.

A few things you can try to debug this:

- Try cranking up the terraform logs (https://www.terraform.io/docs/internals/debugging.html) to see if you can pinpoint which part of the provider routine it is stuck on, or if it is stuck in the go code.
- When it gets stuck, is `terraform` still running when you check the running processes?
- How long does a normal `terraform apply` take? Is it close to 10 minutes? Try extending the go test timeout using `-timeout`. For example, `go test -v -timeout 90m .` will extend the test timeout to 90 minutes.

**Comment by yorinasub17** [comment]
> Changing the terraform debug log level to trace hasnt achieved anything :-(.

Do you see the verbose logging? Can you paste the last few lines coming out of that?

> When it gets stuck following processes are running:

Do you have a local-exec provisioner on one of the resources? What is that calling out to? I wonder if there is some issue with the way terratest is spawning the process such that it is not compatible.

**Comment by r3kzi** [comment]
With `TF_LOG=TRACE` it looks like:

```
TestTerraform 2019-06-17T19:16:30+02:00 command.go:121: CREATE: kubernetes_config_map.istio_service_dashboard
TestTerraform 2019-06-17T19:16:30+02:00 command.go:121:   data.%:                              "" => "1"
```

That's the terraform ressource: 

```
resource "kubernetes_config_map" "istio_service_dashboard" {
  metadata {
    name      = "istio-service-dashboard"
    namespace = "${var.namespace}"

    labels {
      grafana_dashboard = "1"
    }
  }

  data {
    "istio-service-dashboard.json" = "${file("${path.module}/dashboards/istio-service-dashboard.json")}"
  }

  depends_on = ["helm_release.prometheus_operator"]
}
```

No `local-exec` on the ressource that hangs.

**Comment by yorinasub17** [comment]
How big is the json file? Can you try putting in an empty json string (`"{}"`) instead of the `file` call for the `data` block? The place where it hangs suggests it is right where it prints out the json. I am wondering if terratest is hanging because it can't read the output correctly because it is too large.

**Comment by r3kzi** [comment]
It works...

The `.json` is https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/grafana/dashboards/istio-service-dashboard.json

**Comment by yorinasub17** [comment]
Ah ok so in that case, you will have to wait for https://github.com/gruntwork-io/terratest/pull/317 to be merged. Once that is merged, you can set the output max line to something larger.

**Comment by r3kzi** [comment]
thanks for your help!

**Comment by yorinasub17** [comment]
Hi @r3kzi , #317 has been merged and released as https://github.com/gruntwork-io/terratest/releases/tag/v0.17.3. Can you try that out to see if it fixes your bug? You will need to set `OutputMaxLineSize` on `terraform.Options` to something large enough to accommodate your input. Try `128 * 1024` for starters.

**Comment by r3kzi** [comment]
Hi @yorinasub17. It works! :-) Closing this issue...
