### ISSUE TITLE
Running tests against `terraform-aws-rds-example` currently fails

### ISSUE THREAD

**Issue by ggrover** [gruntwork-io/terratest#417]
I'm using terraform v0.12.12, when I execute the following tests `go test -v -run TestTerraformAwsRdsExample` I see the following errors:

```
panic: test timed out after 10m0s

goroutine 46 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/usr/local/Cellar/go/1.13.4/libexec/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 10 minutes]:
testing.tRunner.func1(0xc00050e900)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:885 +0x202
testing.tRunner(0xc00050e900, 0xc00056ddc0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:913 +0xd3
testing.runTests(0xc000349460, 0x4280ea0, 0x1f, 0x1f, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc000270900, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:104 +0x135

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000ded20)
	/Users/gauravg/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/Users/gauravg/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:32 +0x57

goroutine 8 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x428fdc0)
	/Users/gauravg/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/Users/gauravg/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f

goroutine 12 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc000598328)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000598320)
	/usr/local/Cellar/go/1.13.4/libexec/src/sync/waitgroup.go:130 +0x64
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr(0xc00050ea00, 0x3204980, 0xc0002982d8, 0x3204980, 0xc0002982e8, 0xc00055dfc0, 0xc00055dfc0, 0x0, 0x0, 0xc0000f6000)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:136 +0x23d
github.com/gruntwork-io/terratest/modules/shell.runCommandAndStoreOutputE(0xc00050ea00, 0x2e7d180, 0x9, 0xc0000bcd00, 0x1a, 0x1a, 0x2eae101, 0x25, 0xc0002be030, 0x0, ...)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:109 +0x313
github.com/gruntwork-io/terratest/modules/shell.RunCommandAndGetOutputE(0xc00050ea00, 0x2e7d180, 0x9, 0xc0000bcd00, 0x1a, 0x1a, 0x2eae101, 0x25, 0xc0002be030, 0x0, ...)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:57 +0xb2
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE.func1(0xc000719550, 0x106e97c, 0x4278c80, 0xc000519000)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/terraform/cmd.go:61 +0xad
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryableErrorsE.func1(0xc00050ea00, 0x2, 0x31ecd40, 0xc000010018)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/retry/retry.go:118 +0x6b
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE(0xc00050ea00, 0xc0002a6000, 0x167, 0x0, 0x0, 0xc0002af868, 0x7a12368, 0x0, 0x28bbc60, 0xc00055df80)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/retry/retry.go:74 +0x2ff
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryableErrorsE(0xc00050ea00, 0xc0002a6000, 0x167, 0x0, 0x0, 0x0, 0xc000719ac0, 0x1a, 0x104754e, 0x101627a, ...)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/retry/retry.go:117 +0x2a8
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE(0xc00050ea00, 0xc000719ec0, 0xc0000bcd00, 0x1a, 0x1a, 0x1a, 0x1a, 0xc000719bf0, 0x1108514)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/terraform/cmd.go:60 +0x2ea
github.com/gruntwork-io/terratest/modules/terraform.DestroyE(0xc00050ea00, 0xc000719ec0, 0x0, 0x2f2d5a8, 0x719e10, 0xc000719c00)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/terraform/destroy.go:25 +0xc8
github.com/gruntwork-io/terratest/modules/terraform.Destroy(0xc00050ea00, 0xc000719ec0, 0x348bd78, 0xf)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/terraform/destroy.go:11 +0x39
runtime.Goexit()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:563 +0xec
testing.(*common).FailNow(0xc00050ea00)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:653 +0x39
testing.(*common).Fatal(0xc00050ea00, 0xc000719d50, 0x1, 0x1)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:710 +0x78
github.com/gruntwork-io/terratest/modules/aws.GetWhetherSchemaExistsInRdsMySqlInstance(0xc00050ea00, 0xc00067c190, 0x49, 0xcea, 0x2e7bb57, 0x8, 0x2e7b7c7, 0x8, 0x2e7d189, 0x9, ...)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/aws/rds.go:86 +0x114
github.com/gruntwork-io/terratest/test.TestTerraformAwsRdsExample(0xc00050ea00)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/test/terraform_aws_rds_example_test.go:66 +0x860
testing.tRunner(0xc00050ea00, 0x2f2ba80)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:960 +0x350

goroutine 13 [chan receive, 10 minutes]:
testing.runTests.func1.1(0xc00050e900)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1207 +0x3b
created by testing.runTests.func1
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1207 +0xac

goroutine 74 [IO wait]:
internal/poll.runtime_pollWait(0x4d79e68, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000677398, 0x72, 0xb01, 0xb8e, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000677380, 0xc00069e472, 0xb8e, 0xb8e, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_unix.go:169 +0x22b
os.(*File).read(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/os/file_unix.go:259
os.(*File).Read(0xc0002982d8, 0xc00069e472, 0xb8e, 0xb8e, 0xc00007eea8, 0xc0006e2080, 0x2907f60)
	/usr/local/Cellar/go/1.13.4/libexec/src/os/file.go:116 +0x71
bufio.(*Scanner).Scan(0xc000266c80, 0xc000598330)
	/usr/local/Cellar/go/1.13.4/libexec/src/bufio/scan.go:213 +0xa4
github.com/gruntwork-io/terratest/modules/shell.readData(0xc00050ea00, 0xc000266c80, 0xc000598320, 0xc000598330, 0xc00055dfc0)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:151 +0xd7
created by github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:134 +0x1df

goroutine 75 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x4d79cc8, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000677458, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000677440, 0xc000647000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_unix.go:169 +0x22b
os.(*File).read(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/os/file_unix.go:259
os.(*File).Read(0xc0002982e8, 0xc000647000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/os/file.go:116 +0x71
bufio.(*Scanner).Scan(0xc000266d00, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/bufio/scan.go:213 +0xa4
github.com/gruntwork-io/terratest/modules/shell.readData(0xc00050ea00, 0xc000266d00, 0xc000598320, 0xc000598330, 0xc00055dfc0)
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:151 +0xd7
created by github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr
	/Users/gauravg/go/src/github.com/gruntwork-io/terratest/modules/shell/command.go:135 +0x22f
exit status 2
FAIL	github.com/gruntwork-io/terratest/test	600.053s
12.41s user 5.80s system 2% cpu 10:30.11s total
```

Just wondering if the tests, modules and examples under terratest are being kept up to date?

**Comment by brikis98** [comment]
> panic: test timed out after 10m0s

See: https://github.com/gruntwork-io/terratest#timeouts-and-logging

**Comment by brikis98** [comment]
> Just wondering if the tests, modules and examples under terratest are being kept up to date?

Yes.
