### ISSUE TITLE
Cleanup when encountering unexpected error

### ISSUE THREAD

**Issue by hpcsc** [gruntwork-io/terratest#759]
Hi,

Just want to check what's the correct way to cleanup resources (terraform destroy) in case some unexpected error happens? 

An example is when `terraform apply` take more time than timeout period. Look like panic happens in a goroutine and therefore the `defer terraform.Destroy()` statement in main is not called. In this case I need to manually delete the resources

Example test:

```
func TestTerraformMain(t *testing.T) {
	t.Parallel()

	terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		TerraformDir: "./examples/modules/key_vault",
		Vars: map[string]interface{}{
			"environment": strings.ToLower(random.UniqueId()),
		},
	})

	defer terraform.Destroy(t, terraformOptions)

	terraform.InitAndApply(t, terraformOptions)

	output := terraform.Output(t, terraformOptions, "uri")
	require.Equal(t, "Hello, World!", output)
}
```

Error when timeout:

```
TestTerraformMain 2021-01-15T06:01:22Z logger.go:66: module.key_vault.azurerm_key_vault.main: Still creating... [30s elapsed]
panic: test timed out after 1m0s

goroutine 20 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:1618 +0xe5
created by time.goFunc
        /usr/local/go/src/time/sleep.go:167 +0x45

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc000001980)
        /usr/local/go/src/testing/testing.go:1088 +0x24d
testing.tRunner(0xc000001980, 0xc000145de0)
        /usr/local/go/src/testing/testing.go:1127 +0x125
testing.runTests(0xc00000edc0, 0x906a30, 0x1, 0x1, 0xbff869cec03b7964, 0xdf85d19ed, 0x911600, 0x40f250)
        /usr/local/go/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc00014e080, 0x0)
        /usr/local/go/src/testing/testing.go:1345 +0x1eb
main.main()
        _testmain.go:43 +0x138

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc00001b068)
        /usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00001b060)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr(0x779de0, 0xc000001b00, 0x0, 0x775c00, 0xc000010160, 0x775c00, 0xc000010170, 0x0, 0x0, 0xc000014540)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/shell/command.go:149 +0x325
github.com/gruntwork-io/terratest/modules/shell.runCommand(0x779de0, 0xc000001b00, 0x71cbce, 0x9, 0xc000062c60, 0x6, 0x6, 0x723676, 0x1c, 0x0, ...)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/shell/command.go:122 +0x33c
github.com/gruntwork-io/terratest/modules/shell.RunCommandAndGetOutputE(0x779de0, 0xc000001b00, 0x71cbce, 0x9, 0xc000062c60, 0x6, 0x6, 0x723676, 0x1c, 0x0, ...)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/shell/command.go:58 +0x8e
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE.func1(0xc0001876c8, 0x4e5e11, 0x907520, 0x711fa0)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/terraform/cmd.go:77 +0xbc
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryableErrorsE.func1(0x2, 0x774320, 0xc000010018, 0xc0001878f0)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/retry/retry.go:137 +0x78
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE.func1(0x779de0, 0xc000001b00, 0xc0001878f0, 0x1)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/retry/retry.go:68 +0x26
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryInterfaceE(0x779de0, 0xc000001b00, 0xc000148320, 0x50, 0x3, 0x12a05f200, 0xc0001879b0, 0xc0001879e0, 0x6d3300, 0x5adc845c35a285ee, ...)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/retry/retry.go:93 +0x2e2
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryE(0x779de0, 0xc000001b00, 0xc000148320, 0x50, 0x3, 0x12a05f200, 0xc000187a78, 0xc000187aa0, 0x4e9a94, 0xc0000775f0, ...)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/retry/retry.go:68 +0x9b
github.com/gruntwork-io/terratest/modules/retry.DoWithRetryableErrorsE(0x779de0, 0xc000001b00, 0xc000148320, 0x50, 0xc00001f560, 0x3, 0x12a05f200, 0xc000187d20, 0xc00004f550, 0xc000187c90, ...)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/retry/retry.go:136 +0x2de
github.com/gruntwork-io/terratest/modules/terraform.RunTerraformCommandE(0x779de0, 0xc000001b00, 0xc0000142a0, 0xc000062c60, 0x6, 0x6, 0x6, 0x71cbce, 0x9, 0xc00020e340)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/terraform/cmd.go:76 +0x325
github.com/gruntwork-io/terratest/modules/terraform.ApplyE(0x779de0, 0xc000001b00, 0xc0000142a0, 0xc00020e340, 0x2, 0x2, 0xc000016600)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/terraform/apply.go:53 +0xf6
github.com/gruntwork-io/terratest/modules/terraform.InitAndApplyE(0x779de0, 0xc000001b00, 0xc0000142a0, 0xc0001206c0, 0xc0001207d0, 0x0, 0x0)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/terraform/apply.go:31 +0x11e
github.com/gruntwork-io/terratest/modules/terraform.InitAndApply(0x779de0, 0xc000001b00, 0xc0000142a0, 0xb, 0xc00011c868)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/terraform/apply.go:14 +0x45
main-infra-tests.TestTerraformMain(0xc000001b00)
        /app/test/key_vault_test.go:24 +0x186
testing.tRunner(0xc000001b00, 0x732bf0)
        /usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1168 +0x2b3

goroutine 7 [chan receive]:
testing.runTests.func1.1(0xc000001980)
        /usr/local/go/src/testing/testing.go:1444 +0x3b
created by testing.runTests.func1
        /usr/local/go/src/testing/testing.go:1444 +0xac

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7f0828cab760, 0x72, 0x774980)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000630f8, 0x72, 0x774901, 0x8d54c8, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000630e0, 0xc00018d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
os.(*File).read(...)
        /usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000010160, 0xc00018d000, 0x1000, 0x1000, 0x2, 0x2, 0x8e)
        /usr/local/go/src/os/file.go:116 +0x71
bufio.(*Reader).fill(0xc000063260)
        /usr/local/go/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).ReadSlice(0xc000063260, 0x91160a, 0x6c0600, 0xc000206e50, 0x6c0600, 0xc000206e20, 0x6c0600)
        /usr/local/go/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).collectFragments(0xc000063260, 0xc000206e0a, 0xc00004ce18, 0x66bebb, 0x779de0, 0xc000001b00, 0xc00020a2a0, 0x58, 0xc00004ce68, 0x675305, ...)
        /usr/local/go/src/bufio/bufio.go:435 +0x7a
bufio.(*Reader).ReadString(0xc000063260, 0xc00020a20a, 0x58, 0x58, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:483 +0x4c
github.com/gruntwork-io/terratest/modules/shell.readData(0x779de0, 0xc000001b00, 0x0, 0xc000063260, 0x774140, 0xc00000f720, 0x0, 0x0)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/shell/command.go:165 +0x37
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr.func1(0xc00001b060, 0x779de0, 0xc000001b00, 0x0, 0xc000063260, 0xc00000f700, 0xc00004f940)
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/shell/command.go:143 +0x97
created by github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr
        /go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.3/modules/shell/command.go:141 +0x2a9
```

**Comment by robmorgan** [comment]
@hpcsc Hi David,

What command are you using to execute your tests? It looks like there's a very low timeout set... have you tried following the instructions in [Timeouts and logging](https://terratest.gruntwork.io/docs/testing-best-practices/timeouts-and-logging/)?

**Comment by hpcsc** [comment]
hi @robmorgan , yeah in this case I purposely set the timeout when running test to 1m to illustrate the issue. 

For timeout, we can set the timeout period to be large, but wondering whether there's any other case where we need to cleanup manually and what's recommended approach in that case? Can this be handled from terratest itself?

**Comment by robmorgan** [comment]
@hpcsc Ok understood,

At the end of the day, Terratest is simply a library of helper functions that extend Go's default testing package. Therefore it is your responsibility to essentially monitor the tests and their output to ensure that they execute as intended. For our own use-case, we actually use another tool called [cloud-nuke](https://github.com/gruntwork-io/cloud-nuke) to automatically remove any left-over resources on AWS. Note: be very careful if you decide to use that tool. This way we can be confident that something is "garbage-collecting" if a test should ever fail. Feel free to read more of the context in our blog post: https://blog.gruntwork.io/cloud-nuke-how-we-reduced-our-aws-bill-by-85-f3aced4e5876
