### ISSUE TITLE
Timeout readStdoutAndStderr

### ISSUE THREAD

**Issue by lkysow** [gruntwork-io/terratest#816]
👋 thanks for the awesome library! We're seeing weird go test panics due to timeouts and the goroutine trace shows it blocking here: https://github.com/gruntwork-io/terratest/blob/master/modules/shell/command.go#L149

Context is we're doing integration testing by running Kubernetes in Azure and for some reason we only see this error when running `kubectl` commands against Azure and it also just started a couple of days ago so there's definitely more work on our side to figure this out. But thought I'd post here in case anyone has seen this.

Note that the command itself has `--timeout=15m` so the command shouldn't be running 40m

```
    command.go:100: 2021-03-18T01:08:30Z Running command helm with args [install --kubeconfig /home/circleci/.kube/consul-k8s-2979821399 --timeout 15m --namespace default --set connectInject.enabled=true --set connectInject.envoyExtraArgs=--log-level debug --set connectInject.logLevel=debug --set global.acls.manageSystemACLs=true --set global.image=hashicorp/consul-enterprise:1.9.3-ent --set global.imageK8S=docker.mirror.hashicorp.services/hashicorpdev/consul-k8s:latest --set global.tls.enableAutoEncrypt=false --set global.tls.enabled=true --set server.bootstrapExpect=1 --set server.replicas=1 test-v8glor /home/circleci/project]
panic: test timed out after 40m0s
```

```
goroutine 1695 [semacquire]:
sync.runtime_Semacquire(0xc000bd8418)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc000bd8410)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/gruntwork-io/terratest/modules/shell.readStdoutAndStderr(0x1a39ba0, 0xc0006b2000, 0xc0001ce760, 0x1a02ee0, 0xc00081a050, 0x1a02ee0, 0xc00081a060, 0x0, 0xc0001ce760, 0xc000600a80)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.2/modules/shell/command.go:149 +0x305
github.com/gruntwork-io/terratest/modules/shell.runCommand(0x1a39ba0, 0xc0006b2000, 0x17102e6, 0x4, 0xc00000c1e0, 0x1d, 0x1e, 0x170f735, 0x1, 0x0, ...)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.2/modules/shell/command.go:122 +0x333
github.com/gruntwork-io/terratest/modules/shell.RunCommandAndGetOutputE(0x1a39ba0, 0xc0006b2000, 0x17102e6, 0x4, 0xc00000c1e0, 0x1d, 0x1e, 0x170f735, 0x1, 0x0, ...)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.2/modules/shell/command.go:58 +0x8e
github.com/gruntwork-io/terratest/modules/helm.RunHelmCommandAndGetOutputE(0x1a39ba0, 0xc0006b2000, 0xc0004b3c00, 0x1711e67, 0x7, 0xc000754000, 0x1a, 0x30, 0x18, 0x0, ...)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.2/modules/helm/cmd.go:66 +0x2f2
github.com/gruntwork-io/terratest/modules/helm.InstallE(0x1a39ba0, 0xc0006b2000, 0xc0004b3c00, 0xc0003a0680, 0x16, 0xc000926310, 0xb, 0x14f2d60, 0x19dc830)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.2/modules/helm/install.go:49 +0x326
github.com/gruntwork-io/terratest/modules/helm.Install(0x1a39ba0, 0xc0006b2000, 0xc0004b3c00, 0x17150ae, 0xb, 0xc000926310, 0xb)
	/go/pkg/mod/github.com/gruntwork-io/terratest@v0.31.2/modules/helm/install.go:16 +0x77
github.com/hashicorp/consul-helm/test/acceptance/framework/consul.(*HelmCluster).Create(0xc0006e1760, 0xc0006b2000)
	/home/circleci/project/test/acceptance/framework/consul/consul_cluster.go:117 +0xf8
github.com/hashicorp/consul-helm/test/acceptance/tests/connect.TestConnectInject.func1(0xc0006b2000)
	/home/circleci/project/test/acceptance/tests/connect/connect_inject_test.go:50 +0x371
testing.tRunner(0xc0006b2000, 0xc0001ce480)
	/usr/local/go/src/testing/testing.go:1050 +0xdc
created by testing.(*T).Run
```

**Comment by brikis98** [comment]
Hm, weird. I don't think I've seen this issue. Certainly does look like it's waiting on stdin or stdout or stderr and not getting it for some reason. Were you able to find any more info about this?

**Comment by lkysow** [comment]
Not yet but we're going to look this week.
